// Default fallback fonts
export const DEFAULT_FONT_OPTIONS = [
  { name: 'Arial', value: 'Arial, sans-serif' },
  { name: 'Calibri', value: 'Calibri, sans-serif' },
  { name: 'Helvetica', value: 'Helvetica, Arial, sans-serif' },
  { name: 'Times New Roman', value: '"Times New Roman", Times, serif' },
  { name: 'Georgia', value: 'Georgia, serif' },
  { name: 'Courier New', value: '"Courier New", Courier, monospace' },
  { name: 'Verdana', value: 'Verdana, sans-serif' },
  { name: 'Trebuchet MS', value: '"Trebuchet MS", sans-serif' },
  { name: 'Impact', value: 'Impact, Arial Black, sans-serif' },
  { name: 'Comic Sans MS', value: '"Comic Sans MS", cursive' },
  { name: 'Palatino', value: '"Palatino Linotype", Palatino, serif' },
  { name: 'Tahoma', value: 'Tahoma, sans-serif' },
  { name: 'Lucida Console', value: '"Lucida Console", monospace' },
  { name: 'Tajawal', value: '"Tajawal", sans-serif' },
  { name: 'Amiri', value: '"Amiri", serif' },
  { name: 'Dubai', value: '"Dubai", sans-serif' },
];

// Comprehensive font list including system fonts
export const comprehensiveFontList = [
// Basic system fonts
'Arial', 'Arial Black', 'Arial Narrow', 'Arial Unicode MS', 'Arial Bold', 'Arial Italic',
'Helvetica', 'Helvetica Neue', 'Helvetica Light', 'Helvetica Bold', 'Helvetica Condensed',
'Times', 'Times New Roman', 'Times Bold', 'Times Italic',
'Courier', 'Courier New', 'Courier Bold', 'Courier Italic',
'Georgia', 'Georgia Bold', 'Georgia Italic',
'Verdana', 'Verdana Bold', 'Verdana Italic',

// Windows fonts
'Calibri', 'Calibri Light', 'Calibri Bold', 'Calibri Italic',
'Cambria', 'Cambria Bold', 'Cambria Italic', 'Cambria Math',
'Candara', 'Candara Light', 'Candara Bold', 'Candara Italic',
'Century Gothic', 'Century Gothic Bold', 'Century Gothic Italic',
'Comic Sans MS', 'Comic Sans MS Bold',
'Consolas', 'Consolas Bold', 'Consolas Italic',
'Constantia', 'Constantia Bold', 'Constantia Italic',
'Corbel', 'Corbel Light', 'Corbel Bold', 'Corbel Italic',
'Franklin Gothic Medium', 'Franklin Gothic Book', 'Franklin Gothic Demi',
'Garamond', 'Garamond Bold', 'Garamond Italic',
'Impact', 'Impact Bold',
'Lucida Console', 'Lucida Sans Unicode', 'Lucida Grande',
'Microsoft Sans Serif', 'Microsoft YaHei', 'Microsoft JhengHei',
'Palatino Linotype', 'Palatino', 'Palatino Bold', 'Palatino Italic',
'Segoe UI', 'Segoe UI Light', 'Segoe UI Semibold', 'Segoe UI Bold', 'Segoe UI Black',
'Segoe UI Symbol', 'Segoe UI Emoji', 'Segoe UI Historic',
'Tahoma', 'Tahoma Bold',
'Trebuchet MS', 'Trebuchet MS Bold', 'Trebuchet MS Italic',
'Webdings', 'Wingdings', 'Wingdings 2', 'Wingdings 3',
'MS Sans Serif', 'MS Serif', 'Symbol', 'Book Antiqua', 'Bookman Old Style',
'Century', 'Fixedsys', 'Gabriola', 'Marlett', 'Modern', 'Roman', 'Script',
'Small Fonts', 'System', 'Terminal',

// macOS fonts
'SF Pro Display', 'SF Pro Text', 'SF Pro Rounded',
'SF Compact Display', 'SF Compact Text', 'SF Compact Rounded',
'SF Mono', 'SF Arabic', 'SF Armenian', 'SF Georgian',
'Monaco', 'Menlo', 'Menlo Bold', 'Menlo Italic',
'American Typewriter', 'American Typewriter Light', 'American Typewriter Bold',
'Avenir', 'Avenir Light', 'Avenir Medium', 'Avenir Heavy', 'Avenir Black',
'Avenir Next', 'Avenir Next Ultra Light', 'Avenir Next Regular', 'Avenir Next Medium',
'Avenir Next Demi Bold', 'Avenir Next Bold', 'Avenir Next Heavy',
'Avenir Next Condensed', 'Avenir Next Condensed Medium', 'Avenir Next Condensed Demi Bold',
'Baskerville', 'Baskerville Bold', 'Baskerville Italic',
'Big Caslon', 'Big Caslon Medium',
'Bodoni 72', 'Bodoni 72 Oldstyle', 'Bodoni 72 Smallcaps',
'Bradley Hand', 'Bradley Hand Bold',
'Brush Script MT', 'Brush Script MT Italic',
'Chalkboard', 'Chalkboard Bold',
'Chalkboard SE', 'Chalkboard SE Light', 'Chalkboard SE Regular',
'Chalkduster',
'Cochin', 'Cochin Bold', 'Cochin Italic',
'Copperplate', 'Copperplate Light', 'Copperplate Bold',
'Didot', 'Didot Bold', 'Didot Italic',
'Futura', 'Futura Medium', 'Futura Condensed Medium',
'Geneva', 'Geneva Bold',
'Gill Sans', 'Gill Sans Light', 'Gill Sans UltraBold',
'Hoefler Text', 'Hoefler Text Black',
'Marker Felt', 'Marker Felt Thin', 'Marker Felt Wide',
'Noteworthy', 'Noteworthy Light', 'Noteworthy Bold',
'Optima', 'Optima Regular', 'Optima Bold',
'Papyrus', 'Papyrus Condensed',
'Phosphate', 'Phosphate Inline', 'Phosphate Solid',
'Rockwell', 'Rockwell Regular', 'Rockwell Bold',
'Savoye LET', 'SignPainter', 'Skia', 'Skia Regular',
'Snell Roundhand', 'Snell Roundhand Bold',
'Zapfino',

// Linux fonts
'Ubuntu', 'Ubuntu Light', 'Ubuntu Regular', 'Ubuntu Medium', 'Ubuntu Bold',
'Ubuntu Mono', 'Ubuntu Condensed',
'Cantarell', 'Cantarell Regular', 'Cantarell Bold',
'DejaVu Sans', 'DejaVu Sans Light', 'DejaVu Sans Bold',
'DejaVu Sans Mono', 'DejaVu Sans Mono Bold',
'DejaVu Serif', 'DejaVu Serif Bold',
'Liberation Sans', 'Liberation Sans Narrow', 'Liberation Serif', 'Liberation Mono',
'Noto Sans', 'Noto Serif', 'Noto Mono',
'Droid Sans', 'Droid Sans Mono', 'Droid Serif',
'Source Sans Pro', 'Source Serif Pro', 'Source Code Pro',
'Roboto', 'Roboto Light', 'Roboto Regular', 'Roboto Medium', 'Roboto Bold', 'Roboto Black',
'Roboto Condensed', 'Roboto Mono', 'Roboto Slab',

// Google Fonts (commonly installed)
'Open Sans', 'Open Sans Light', 'Open Sans Regular', 'Open Sans Semibold', 'Open Sans Bold',
'Open Sans Condensed',
'Lato', 'Lato Light', 'Lato Regular', 'Lato Bold', 'Lato Black',
'Montserrat', 'Montserrat Light', 'Montserrat Regular', 'Montserrat Medium', 'Montserrat Bold',
'Poppins', 'Poppins Light', 'Poppins Regular', 'Poppins Medium', 'Poppins Bold',
'Nunito', 'Nunito Light', 'Nunito Regular', 'Nunito Bold',
'Inter', 'Inter Light', 'Inter Regular', 'Inter Medium', 'Inter Bold',
'Playfair Display', 'Playfair Display Regular', 'Playfair Display Bold',
'Merriweather', 'Merriweather Light', 'Merriweather Regular', 'Merriweather Bold',
'PT Sans', 'PT Serif', 'PT Mono',
'Oswald', 'Oswald Light', 'Oswald Regular', 'Oswald Medium', 'Oswald Bold',
'Raleway', 'Raleway Light', 'Raleway Regular', 'Raleway Medium', 'Raleway Bold',
'Slabo 27px', 'Slabo 13px',
'Fira Sans', 'Fira Sans Light', 'Fira Sans Regular', 'Fira Sans Medium', 'Fira Sans Bold',
'Work Sans', 'Work Sans Light', 'Work Sans Regular', 'Work Sans Medium', 'Work Sans Bold',
'IBM Plex Sans', 'IBM Plex Serif', 'IBM Plex Mono',

// Programming fonts
'Fira Code', 'Fira Code Light', 'Fira Code Regular', 'Fira Code Medium', 'Fira Code Bold',
'JetBrains Mono', 'JetBrains Mono Light', 'JetBrains Mono Regular', 'JetBrains Mono Bold',
'Cascadia Code', 'Cascadia Mono',
'Inconsolata', 'Inconsolata Regular', 'Inconsolata Bold',
'Operator Mono', 'Operator Mono Light', 'Operator Mono Book',
'Courier Prime', 'Courier Prime Regular', 'Courier Prime Bold',
'Anonymous Pro', 'Anonymous Pro Regular', 'Anonymous Pro Bold',
'Input Mono', 'Input Sans', 'Input Serif',
'Dank Mono', 'Victor Mono',

// International fonts
'Amiri', 'Amiri Regular', 'Amiri Bold',
'Cairo', 'Cairo Light', 'Cairo Regular', 'Cairo Bold',
'Dubai', 'Dubai Light', 'Dubai Regular', 'Dubai Medium', 'Dubai Bold',
'Harmattan', 'Lateef', 'Markazi Text',
'Noto Sans Arabic', 'Noto Naskh Arabic', 'Noto Kufi Arabic',
'Reem Kufi', 'Scheherazade', 'Tajawal',
'Aref Ruqaa', 'Changa', 'El Messiri', 'Lalezar', 'Mada', 'Rakkas',
'Hacen Algeria', 'Hacen Tunisia', 'Hacen Morocco',

// Chinese fonts
'PingFang SC', 'PingFang TC', 'PingFang HK',
'Microsoft YaHei', 'Microsoft YaHei UI',
'SimHei', 'SimSun', 'SimKai', 'SimLi',
'STHeiti', 'STSong', 'STKaiti', 'STFangsong',
'Hiragino Sans GB', 'Hiragino Sans CN',
'Source Han Sans SC', 'Source Han Sans TC', 'Source Han Sans HC',
'Noto Sans CJK SC', 'Noto Sans CJK TC', 'Noto Sans CJK HK',

// Japanese fonts
'Hiragino Kaku Gothic Pro', 'Hiragino Kaku Gothic ProN',
'Hiragino Mincho Pro', 'Hiragino Mincho ProN',
'Yu Gothic', 'Yu Gothic UI', 'Yu Gothic Medium', 'Yu Gothic Light',
'Yu Mincho', 'Yu Mincho Light', 'Yu Mincho Demibold',
'Meiryo', 'Meiryo UI',
'MS Gothic', 'MS UI Gothic', 'MS PGothic',
'MS Mincho', 'MS PMincho',
'Source Han Sans JP', 'Noto Sans CJK JP',

// System generic fonts
'system-ui', '-apple-system', 'BlinkMacSystemFont',
'sans-serif', 'serif', 'monospace', 'cursive', 'fantasy',

// Additional Windows fonts
'Ebrima', 'Gabriola', 'Gadugi', 'HoloLens MDL2 Assets',
'Javanese Text', 'Leelawadee UI', 'Malgun Gothic', 'Microsoft Himalaya',
'Microsoft New Tai Lue', 'Microsoft PhagsPa', 'Microsoft Tai Le',
'Microsoft Uighur', 'MingLiU', 'Mongolian Baiti', 'MV Boli',
'Myanmar Text', 'Nirmala UI', 'PMingLiU', 'Segoe MDL2 Assets',
'Segoe Print', 'Segoe Script', 'SimSun-ExtB', 'Sylfaen',
'Yu Gothic UI Light', 'Yu Gothic UI Semilight', 'Yu Gothic UI Semibold'
];
